spring:
  profiles:
    group:
      "local": "testdb,common"
      "dev":  "dev,common"
      "prod": "proddb,common"

---

spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mariadb://localhost:3306/t-admin
    username: haein
    password: 2849

  second-datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mariadb://localhost:3306/godhavi
    username: haein
    password: 2849

image:
  path: D:\\temp\\  #이미지 파일을 저장할 폴더경로(서버에 저장할 폴더경로)
  server: 172.23.206.226
  port: 8082

custom:
  path:
    upload-images: D:/temp/  #이미지 파일을 저장할 폴더경로

---

spring:
  config:
    activate:
      on-profile: "common"
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    properties:
      open-in-view: false
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8081

jwt:
  secret: BIGELEPHANTBLACKTIRTLE1@34!@weee56