spring:
  profiles:
    group:
      "local": "testdb,common"
      "dev":  "dev,common"
      "prod": "proddb,common"

---

spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

---

spring:
  config:
    activate:
      on-profile: "testdb"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

---

spring:
  config:
    activate:
      on-profile: "common"
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

server:
  port: 8081

jwt:
  secret: BIGELEPHANTBLACKTIRTLE1@34!@weee56